//! KAT(known-answer test) 벡터 생성기 — frozen 파라미터 회귀용.
//! `cargo run --example gen_kat`로 실행해 `tests/kat.rs`의 기대값을 갱신.

use ypsilenti::YpsiBuilder;
use std::hash::Hasher;

fn hx(b: &[u8]) -> String {
    b.iter().map(|x| format!("{:02x}", x)).collect()
}

fn unkeyed(data: &[u8]) -> ([u8; 16], u64) {
    let b = YpsiBuilder::unkeyed();
    let mut h = b.build_hasher();
    h.update(data);
    let d = h.clone().finalize();
    let u = h.finalize_u64();
    (d, u)
}

fn keyed(key: &[u8], data: &[u8]) -> ([u8; 16], u64) {
    let b = YpsiBuilder::keyed(key);
    let mut h = b.build_hasher();
    h.update(data);
    let d = h.clone().finalize();
    let u = h.finalize_u64();
    (d, u)
}

fn main() {
    // single-leaf limit = T_MAX * BLOCK_BYTES = 8 * 32 = 256
    let p200: Vec<u8> = (0..200u32).map(|i| i as u8).collect();
    let leaf_full = vec![0xABu8; 256]; // exactly 1 leaf
    let tree2 = vec![0xCDu8; 257]; // → tree mode
    let tree_big: Vec<u8> = (0..4096u32).map(|i| (i.wrapping_mul(7) ^ 0x5A) as u8).collect();
    let key16 = b"0123456789abcdef";

    let cases: &[(&str, ([u8; 16], u64))] = &[
        ("unkeyed empty", unkeyed(b"")),
        ("unkeyed abc", unkeyed(b"abc")),
        ("unkeyed 0..200", unkeyed(&p200)),
        ("unkeyed leaf_full(256)", unkeyed(&leaf_full)),
        ("unkeyed tree(257)", unkeyed(&tree2)),
        ("unkeyed tree_big(4096)", unkeyed(&tree_big)),
        ("keyed[0;16] abc", keyed(&[0u8; 16], b"abc")),
        ("keyed[ascii] abc", keyed(key16, b"abc")),
        ("keyed[ascii] tree_big", keyed(key16, &tree_big)),
    ];
    println!("// ypsilenti KAT — frozen params v1 (auto-generated by examples/gen_kat.rs)");
    for (name, (d, u)) in cases {
        println!("    (\"{}\", \"{}\", {:#018x}),", name, hx(d), u);
    }
}
